apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: observer-prod
commonLabels:
  app: observer-prod

resources:
  - namespace.yaml
  - observer-sa.yaml
  - observer-token-secret.yaml
  - observer-cronjob.yaml