apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "417"
  commitHash: 0b05bc0d86206787104ac9c22fa46d0932dea5e4
  deployed: "1762448991"
  env: vsphere
