apiVersion: v1
kind: ConfigMap
metadata:
  name: thinkingengine-configmap
  namespace: thinkingengine
  labels:
    bot: conformitron
data:
  Namespace: thinkingengine
  prNumber: "402"
  commitHash: 3d578128ab225160ab1f6dace05dc86e9dfdf194
  deployed: "1763978851"
  env: common
