apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "416"
  commitHash: 35ea2c32a6c8439012741b703c33e0b426dee4f1
  deployed: "1762279816"
  env: cloud
