apiVersion: v1
kind: ConfigMap
metadata:
  name: zilliz-milvus-configmap
  namespace: zilliz-milvus
  labels:
    bot: conformitron
data:
  Namespace: zilliz-milvus
  prNumber: "421"
  commitHash: 63bd44a1837e1d7fac7f1fc250591288481ad5d6
  deployed: "1765835631"
  env: common
