apiVersion: v1
kind: ConfigMap
metadata:
  name: zilliz-milvus-configmap
  namespace: zilliz-milvus
  labels:
    bot: conformitron
data:
  Namespace: zilliz-milvus
  prNumber: "421"
  commitHash: 2e5943bedbc7f860733d09625bcc8e30319fb3b9
  deployed: "1765821283"
  env: common
