apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "428"
  commitHash: 443d702268d79b2f233a081dc1e5c2162df8af98
  deployed: "1766006831"
  env: nodes
