apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "430"
  commitHash: 29919c57abf6f90f289a044597f07924a84bb5f8
  deployed: "1767121022"
  env: nodes
