apiVersion: v1
kind: ConfigMap
metadata:
  name: tetrate-istio-system-configmap
  namespace: tetrate-istio-system
  labels:
    bot: conformitron
data:
  Namespace: tetrate-istio-system
  prNumber: "245"
  commitHash: 2d3025491be327fe73c6769ba1dbc6d5fc422da9
  deployed: "1713927450"
  env: common
