apiVersion: v1
kind: ConfigMap
metadata:
  name: risingwave-configmap
  namespace: risingwave
  labels:
    bot: conformitron
data:
  Namespace: risingwave
  prNumber: "403"
  commitHash: 7b50060fd2888b73e886f30455718ceaac219cbe
  deployed: "1764211977"
  env: common
