apiVersion: v1
kind: ConfigMap
metadata:
  name: risingwave-configmap
  namespace: risingwave
  labels:
    bot: conformitron
data:
  Namespace: risingwave
  prNumber: "403"
  commitHash: af33745e4db4cc0104bc1fc96bb8b100978b7164
  deployed: "1764713789"
  env: common
