apiVersion: v1
kind: ConfigMap
metadata:
  name: risingwave-configmap
  namespace: risingwave
  labels:
    bot: conformitron
data:
  Namespace: risingwave
  prNumber: "403"
  commitHash: 0482cfa715d9e5a77e415984ec1a412c6d0b6d1e
  deployed: "1762238421"
  env: common
