apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "426"
  commitHash: 30a7b8c249bd8a080fd98ea2757aa98c56285954
  deployed: "1765322437"
  env: baremetal
