apiVersion: v1
kind: ConfigMap
metadata:
  name: datakit-configmap
  namespace: datakit
  labels:
    bot: conformitron
data:
  Namespace: datakit
  prNumber: "419"
  commitHash: 24cac59b07822ef9373459d990a788134b531c3a
  deployed: "1763360013"
  env: common
